package web

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"net/http/cookiejar"
	"net/http/httptest"
	"net/url"
	"path/filepath"
	"strings"
	"testing"
	"time"

	jose "github.com/go-jose/go-jose/v4"
	"github.com/go-jose/go-jose/v4/jwt"
	"github.com/jeessy2/ddns-go/v6/config"
	"github.com/jeessy2/ddns-go/v6/util"
)

func TestOIDCFlow(t *testing.T) {
	// The test provider signs real ID tokens; the application verifies discovery,
	// JWKS, issuer, audience, expiry and nonce using go-oidc, not a mocked verifier.
	t.Setenv(util.ConfigFilePathENV, filepath.Join(t.TempDir(), "config.yaml"))
	key, _ := rsa.GenerateKey(rand.Reader, 2048)
	signingKey := jose.JSONWebKey{Key: key, KeyID: "test-key", Algorithm: string(jose.RS256), Use: "sig"}
	signer, _ := jose.NewSigner(jose.SigningKey{Algorithm: jose.RS256, Key: signingKey}, nil)
	var issuer, nonce, challenge, variant string
	provider := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch r.URL.Path {
		case "/.well-known/openid-configuration":
			json.NewEncoder(w).Encode(map[string]any{"issuer": issuer, "authorization_endpoint": issuer + "/authorize", "token_endpoint": issuer + "/token", "jwks_uri": issuer + "/keys", "id_token_signing_alg_values_supported": []string{"RS256"}})
		case "/keys":
			json.NewEncoder(w).Encode(jose.JSONWebKeySet{Keys: []jose.JSONWebKey{signingKey.Public()}})
		case "/token":
			r.ParseForm()
			sum := sha256.Sum256([]byte(r.Form.Get("code_verifier")))
			user, secret, _ := r.BasicAuth()
			if user != "test-client" || secret != "test-secret" || r.Form.Get("code") != "test-code" || base64.RawURLEncoding.EncodeToString(sum[:]) != challenge {
				http.Error(w, "invalid exchange", 400)
				return
			}
			// A standards-only provider need not return any username or group claims.
			claims := map[string]any{"iss": issuer, "sub": "user-123", "aud": "test-client", "exp": time.Now().Add(time.Hour).Unix(), "iat": time.Now().Unix(), "nonce": nonce}
			switch variant {
			case "nonce":
				claims["nonce"] = "wrong"
			case "audience":
				claims["aud"] = "other"
			case "issuer":
				claims["iss"] = "https://other.invalid"
			case "expired":
				claims["exp"] = time.Now().Add(-time.Hour).Unix()
			case "missing subject":
				delete(claims, "sub")
			case "custom claims":
				claims["groups"] = map[string]any{"custom": 42}
				claims["preferred_username"] = "unrelated-local-name"
			}
			currentSigner := signer
			if variant == "signature" {
				other, _ := rsa.GenerateKey(rand.Reader, 2048)
				currentSigner, _ = jose.NewSigner(jose.SigningKey{Algorithm: jose.RS256, Key: jose.JSONWebKey{Key: other, KeyID: "test-key"}}, nil)
			}
			raw, _ := jwt.Signed(currentSigner).Claims(claims).Serialize()
			json.NewEncoder(w).Encode(map[string]any{"access_token": "unused", "token_type": "Bearer", "id_token": raw})
		default:
			http.NotFound(w, r)
		}
	}))
	defer provider.Close()
	issuer = provider.URL
	oldClient := oidcHTTPClient
	oidcHTTPClient = provider.Client()
	defer func() { oidcHTTPClient = oldClient }()
	oidcSessions = newOIDCSessions()
	mux := http.NewServeMux()
	mux.HandleFunc("/oidc/start", OIDCStart)
	mux.HandleFunc("/oidc/callback", OIDCCallback)
	mux.HandleFunc("/private", Auth(func(w http.ResponseWriter, r *http.Request) { w.Write([]byte("private")) }))
	mux.HandleFunc("/oidc-settings", Auth(OIDCSettings))
	mux.HandleFunc("/oidc-settings/save", Auth(SaveOIDCSettings))
	mux.HandleFunc("/logout", Auth(Logout))
	app := httptest.NewTLSServer(SessionMiddleware(mux))
	defer app.Close()
	conf := config.Config{}
	conf.Username = "local"
	conf.Password = "existing-hash"
	if err := conf.SaveConfig(); err != nil {
		t.Fatal(err)
	}
	// First setup supplies only the visible connection fields and the callback
	// generated by the UI. No preexisting OIDC configuration or local-name match.
	setup, _ := json.Marshal(map[string]any{"Enabled": true, "Issuer": issuer, "ClientID": "test-client", "ClientSecret": "test-secret", "RedirectURL": app.URL + "/oidc/callback"})
	setupResponse := httptest.NewRecorder()
	SaveOIDCSettings(setupResponse, httptest.NewRequest(http.MethodPost, "/oidc-settings/save", strings.NewReader(string(setup))))
	if setupResponse.Code != http.StatusOK {
		t.Fatalf("first setup failed: %s", setupResponse.Body.String())
	}
	conf, _ = config.GetConfigCached()
	if conf.OIDC.Scopes != "openid" || !conf.OIDC.AutoLogin {
		t.Fatal("incorrect first-setup defaults")
	}
	newClient := func() *http.Client {
		c := *app.Client()
		c.Jar, _ = cookiejar.New(nil)
		c.CheckRedirect = func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }
		return &c
	}
	get := func(c *http.Client, path string) *http.Response {
		t.Helper()
		r, err := c.Get(app.URL + path)
		if err != nil {
			t.Fatal(err)
		}
		return r
	}
	start := func(c *http.Client) string {
		t.Helper()
		r := get(c, "/oidc/start")
		defer r.Body.Close()
		if r.StatusCode != 302 {
			b, _ := io.ReadAll(r.Body)
			t.Fatalf("start %d %s", r.StatusCode, b)
		}
		u, _ := url.Parse(r.Header.Get("Location"))
		q := u.Query()
		nonce = q.Get("nonce")
		challenge = q.Get("code_challenge")
		if q.Get("code_challenge_method") != "S256" {
			t.Fatal("missing PKCE")
		}
		if q.Get("scope") != "openid" {
			t.Fatal("login should not require profile or group scopes")
		}
		return q.Get("state")
	}
	for _, v := range []string{"state", "nonce", "audience", "issuer", "expired", "signature", "missing subject", "provider denied", "custom claims", "success"} {
		t.Run(v, func(t *testing.T) {
			variant = v
			c := newClient()
			state := start(c)
			if v == "state" {
				state = "wrong"
			}
			path := "/oidc/callback?code=test-code&state=" + url.QueryEscape(state)
			if v == "provider denied" {
				path = "/oidc/callback?error=access_denied&state=" + url.QueryEscape(state)
			}
			r := get(c, path)
			io.Copy(io.Discard, r.Body)
			r.Body.Close()
			want := 401
			if v == "success" || v == "custom claims" {
				want = 200
			}
			if r.StatusCode != want {
				t.Fatalf("callback %d, want %d", r.StatusCode, want)
			}
			r = get(c, "/private")
			r.Body.Close()
			want = 303
			if v == "success" || v == "custom claims" {
				want = 200
			}
			if r.StatusCode != want {
				t.Fatalf("private %d, want %d", r.StatusCode, want)
			}
			r = get(c, path)
			r.Body.Close()
			if r.StatusCode != 401 {
				t.Fatal("callback replay accepted")
			}
		})
	}
	variant = "success"
	c := newClient()
	state := start(c)
	// An independent browser cannot use a captured authorization state.
	stranger := newClient()
	r := get(stranger, "/oidc/callback?code=test-code&state="+state)
	r.Body.Close()
	if r.StatusCode != 401 {
		t.Fatal("unbound callback accepted")
	}
	r = get(c, "/oidc/callback?code=test-code&state="+state)
	r.Body.Close()
	if r.StatusCode != 200 {
		t.Fatal("valid callback rejected")
	}
	r = get(c, "/oidc-settings")
	r.Body.Close()
	if r.StatusCode != http.StatusSeeOther || r.Header.Get("Location") != "/#oidc" {
		t.Fatal("settings should redirect to the dashboard tab")
	}
	// The settings API preserves a blank secret and never rewrites DNS settings.
	settings, _ := json.Marshal(map[string]any{"Enabled": true, "Issuer": conf.OIDC.Issuer, "ClientID": conf.OIDC.ClientID, "ClientSecret": ""})
	request, _ := http.NewRequest(http.MethodPost, app.URL+"/oidc-settings/save", strings.NewReader(string(settings)))
	request.Header.Set("Content-Type", "application/json")
	r, err := c.Do(request)
	if err != nil {
		t.Fatal(err)
	}
	r.Body.Close()
	saved, _ := config.GetConfigCached()
	if r.StatusCode != 200 || saved.OIDC.ClientSecret != "test-secret" || saved.Password != conf.Password {
		t.Fatal("settings save lost the stored secret or local login")
	}
	if saved.OIDC.RedirectURL != conf.OIDC.RedirectURL || saved.OIDC.Scopes != conf.OIDC.Scopes || saved.OIDC.AutoLogin != conf.OIDC.AutoLogin {
		t.Fatal("compact settings changed omitted OIDC settings")
	}
	w := httptest.NewRecorder()
	Writing(w, httptest.NewRequest(http.MethodGet, "/", nil))
	if strings.Contains(w.Body.String(), "test-secret") || !strings.Contains(w.Body.String(), `id="OIDCClientSecret"`) || !strings.Contains(w.Body.String(), `id="account-panel"`) {
		t.Fatal("dashboard must render the account/OIDC tabs without the secret")
	}
	if strings.Contains(w.Body.String(), "OIDCAllowedUsers") || strings.Contains(w.Body.String(), "OIDCAllowedGroups") {
		t.Fatal("provider-specific access controls should not be rendered")
	}
	// CSRF is enforced on writes but cross-origin top-level navigation is safe.
	req, _ := http.NewRequest("POST", app.URL+"/oidc-settings/save", strings.NewReader(`{}`))
	req.Header.Set("Origin", "https://attacker.invalid")
	req.Header.Set("Sec-Fetch-Site", "cross-site")
	r, _ = c.Do(req)
	r.Body.Close()
	if r.StatusCode != 403 {
		t.Fatal("cross-origin write accepted")
	}
	req, _ = http.NewRequest("GET", app.URL+"/private", nil)
	req.Header.Set("Sec-Fetch-Site", "same-site")
	r, _ = c.Do(req)
	r.Body.Close()
	if r.StatusCode != 200 {
		t.Fatal("safe OIDC redirect blocked")
	}
	// Disabling OIDC invalidates issued application sessions immediately.
	conf.OIDC.Enabled = false
	if err := conf.SaveConfig(); err != nil {
		t.Fatal(err)
	}
	r = get(c, "/private")
	r.Body.Close()
	if r.StatusCode != 303 {
		t.Fatal("stale OIDC session accepted")
	}
	// Local recovery login remains independent of OIDC availability.
	cookieInSystem = &http.Cookie{Name: cookieName, Value: "local-test-session", Expires: time.Now().Add(time.Hour)}
	u, _ := url.Parse(app.URL)
	c.Jar.SetCookies(u, []*http.Cookie{{Name: cookieName, Value: cookieInSystem.Value, Path: "/"}})
	r = get(c, "/private")
	r.Body.Close()
	if r.StatusCode != 200 {
		t.Fatal("local recovery session rejected")
	}
	req, _ = http.NewRequest(http.MethodPost, app.URL+"/logout", nil)
	r, err = c.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	r.Body.Close()
	if r.StatusCode != 302 {
		t.Fatal("logout failed")
	}
	if r.Header.Get("Location") != "/login?local=1" {
		t.Fatal("logout would immediately trigger automatic OIDC login")
	}
	r = get(c, "/private")
	r.Body.Close()
	if r.StatusCode != 303 {
		t.Fatal("session still valid after logout")
	}
}
